version: "3.8"
services:
  client:
    image: hyperfigures-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9500:9500"
    volumes:
      - .:/app:delegated # Use delegated for better performance on macOS
      # - /app/node_modules # Ensure this line is not present to avoid conflicts with node_modules

volumes:
   app: 